The first 3 sections of the ruby course (intro, numbers and bools)
roa-sh/ruby_path pull request #1
Opened 2021-06-02 16:39 UTC by roa-sh

Hi esteban, this is my first PR.
I created another branch called my_work, here i'm uploading my files, and then i'll ask you for a PR for merging with main branch.

Thanks!

2021-06-02 23:00 UTC, roa-sh commented
Hi esteban, i continued working and added the section 4,5, and 6.

2021-06-02 23:11 UTC, estebancordoba requested changes
I recommend you read the ruby style guide: https://github.com/rubocop/ruby-style-guide, it is also part of the path

2021-06-02 23:11 UTC, estebancordoba commented on 2section_getting_started.rb
> +#and can prints aritmetic operations too
for comments put a space after the # (https://github.com/rubocop/ruby-style-guide#hash-space)

2021-06-02 23:11 UTC, estebancordoba commented on 2section_getting_started.rb
> +#-----------------The puts method---------
Avoid hyphenated comments

2021-06-02 23:11 UTC, estebancordoba commented on 5section_methods_plus_calc.rb
> +    # p "in odd"
For the indentation use 2 spaces: https://github.com/rubocop/ruby-style-guide#spaces-indentation

2021-06-02 23:11 UTC, estebancordoba commented on 6section_methods_conditionals2.rb
> +        case credentials
Fix the indentation please

2021-06-03 13:09 UTC, roa-sh commented
Ok esteban, i'll review the guide and apply changes.

2021-06-03 14:18 UTC, roa-sh commented
Hi, @estebancordoba i fixed the things you commented me. Thnaks for the rubocop recomendation, i started using it as my linter and also helped me to the good practices in coding.

2021-06-03 14:31 UTC, estebancordoba approved these changes

2021-06-03 14:33 UTC, merged